# Numpy

#### 1)Python prgrm to create an array and converted to a desired dimension.

In [17]:
import numpy as np
arr=np.array([[8,9,10],[11,12,13]])
print(arr)

[[ 8  9 10]
 [11 12 13]]


In [18]:
print(arr.reshape(3,2))

[[ 8  9]
 [10 11]
 [12 13]]


#### 2) Create an array and extract particular set of elements from the array

In [49]:
arr1=np.array([[8,9],[10,11],[12,13]])
print(arr1)

[[ 8  9]
 [10 11]
 [12 13]]


In [50]:
print(arr1[0:2,1,])

[ 9 11]
